services:
  server-main:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: server-main
    command: ["MAIN"]
    ports:
      - "5000:5000"

  server-backup:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: server-backup
    command: ["BACKUP"]
    ports:
      - "5001:5001"

  client-template:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    image: chat-distribuido-client
    profiles: ["manual"]
    stdin_open: true
    tty: true